### ISSUE TITLE
some *aliases.json.gz is failed

### ISSUE THREAD

**Issue by shenweima** [plantinformatics/pretzel#141]
In the last step,
```
for F in *_aliases.json.gz; do
  echo -ne "\n${F}\t"
  curl -X POST --header 'Content-Type: application/json'   \
  --header 'Accept: application/json' -H'Content-Encoding: gzip' \
  --data-binary @${F}   \
  "${SRV}/api/Aliases/bulkCreate?access_token=${TOKEN}"
done
```
some aliases.json.gz is ok, but some is not work.
![image](https://user-images.githubusercontent.com/8536868/60379423-f50a2280-9a64-11e9-8e4e-bb232002f6df.png)

**Comment by Don-Isdale** [comment]
Thanks - we'll retest that.
If you have access to the server log, it would be interesting to see what it logged at the time of that error.
Loading the aliases can be demanding on memory, so it may exceed some host capacity.

**Comment by shenweima** [comment]
```
/app/node_modules/raw-body/index.js:252
      buffer += decoder.write(chunk)
                        ^

RangeError: Invalid string length
    at IncomingMessage.onData (/app/node_modules/raw-body/index.js:252:25)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:135:22)
```

**Comment by rsuchecki** [comment]
The fact that the problem arises on uploading aliases for low confidence (LC) gene predictions suggests it may be related to host resources as indicated by @Don-Isdale. In the first instance you may try excluding any of the `*LC*_aliases.json.gz` files.

**Comment by Don-Isdale** [comment]
Thanks shenweima for the error from the server log.

As mentioned the alias json files are simple arrays, so you can split them :
  < some_aliases.json jq -c '.[]'  | split --lines=10000 - aSplit
  for i in aSplit*; do < $i jq -s . | uploadAliases -; done

You can probably just re-load the files which didn't load, but if they have partially loaded you may need to create a data file with just the aliases which didn't load.  (you can drop all aliases and start again with : db.Alias.drop())
You can see which aliases loaded OK with (mongo shell, db admin) e.g. db.Alias.find({"string2" : "BobWhite_c10015_641"}).
You could filter those out of the alias json and reload the reduced data, e.g. :
  < some_aliases.json jq -c '.[]'  | grep -v '"AET1Gv20001000".*"TraesCS1D01G003700LC"' | jq -s . > some_aliases.remainder.json
(that example matches on both feature names of the alias - string1 and string2; order matters;  for larger numbers of filters you would probably sed, e.g. /"AET1Gv20001000".*"TraesCS1D01G003700LC"/d)

uploadAliases() can be defined using pretzel/resources/tools/functions_prod.bash
something like : function uploadAliases()  { export URL=$URL_A; uploadData $* }

(refn: https://stedolan.github.io/jq)

**Comment by rsuchecki** [comment]
closing due to inactivity
