### ISSUE TITLE
Feature / marker names which are numbers are being converted to numeric type instead of string

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#404]
#### Introduction

The following evidence suggests that marker names uploaded in spreadsheets are being converted to numbers, and this is causing problems in matching QTL Flanking Markers to the parent dataset, and in aligning paths between datasets.  It may be that the marker names are being converted to numbers in the parent and not in the child dataset.

#### Test Evidence and Required Changes

While uploading a QTL dataset via a spreadsheet, it is getting this error (in network tab, in Pretzel it says [object Object]):
            Error: X : Dataset name &quot;X &quot;error : Block 5H Feature F Flanking Markers N are not in parent P name 5H<br>
- [x] ensure this error is displayed in the GUI
This has since been implemented, noted in #428

After deleting the QTL which was defining a single SNP, where the error was coming from, the upload then worked, but no paths are displayed when expected.
(for example, marker name N2 which worked previously)

(note : X, P are dataset names, F is a feature name,  N and N2 are marker numbers)

```
vendor-cb6ea279aadda3faa80311bb4c32d111.js:1979 Uncaught TypeError: e.match is not a function
    at e.featureNameClass (pretzel-frontend-441133ffab17e3f19a7ba70aaae17cdd.js:6054:187)
    at Object.featureEltId (pretzel-frontend-441133ffab17e3f19a7ba70aaae17cdd.js:6296:32)
```

- [x] check the type conversion of numbers in spreadsheet upload - this should not apply to the name field.
fe6ea2c8 datasets upload : convert numeric feature names to string; delay to enable dependency checking between datasets in a single spreadsheet

This commit fe6ea2c8 also implements the following item :
- [x] in featureNameClass(), handle name being of type other than 'string', e.g. 'number'.
This function assumes that name is a string (possibly a string of numbers) :
```
 frontend/app/utils/draw/stacksAxes.js :
...
function featureNameClass(name)
...
  if (name.match(/[0-9]/))
```

---

**Comment by Don-Isdale** [comment]
#### Test Results : OK

The original spreadsheet which revealed this issue was used in testing, after this commit, and the earlier issue #428 :
 fe6ea2c8 datasets upload : convert numeric feature names to string; delay to enable dependency checking between datasets in a single spreadsheet

Screenshots of the results were kept;  they are not included here because the spreadsheet data is not public.
The spreadsheet is  : `  381786 2022-10-06 13:46 DArT-Seq Markers_....._........_2019_Pretzel.xlsx`
