### ISSUE TITLE
Need more error reporting to user after upload error

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#53]
tried to upload pretzel-data/myDataset.json, which had already been uploaded.
no error message was displayed in the browser tab.

browser : Web Inspector console log :
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
data-base.js:30 Object
details of that error : 
...
11000
errmsg
:
"insertDocument :: caused by :: 11000 E11000 duplicate key error index: admin.Dataset.$_id_  dup key: { : "myGenome" }"
index
:
0

server log :
Unhandled error for request POST /api/Datasets/upload: MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: admin.Dataset.$_id_  dup key: { : "myGenome" }
    at Function.MongoError.create ($MMVp_be/backend/node_modules/mongodb-core/lib/error.js:31:11)
    at toError ($MMVp_be/backend/node_modules/mongodb/lib/utils.js:139:22)
    at $MMVp_be/backend/node_modules/mongodb/lib/collection.js:669:23
    at handleCallback ($MMVp_be/backend/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler ($MMVp_be/backend/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at $MMVp_be/backend/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
127.0.0.1 - - [05/Jun/2018:07:46:18 +0000] "POST /api/Datasets/upload HTTP/1.1" 500 - "http://localhost:4200/matrixview" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"

**Comment by Gruek** [comment]
Added error message for user in commit: afa987824ebb5f66d6362e7852b310bb969f4bf2
