### ISSUE TITLE
Uniqueness of dataset names 

### ISSUE THREAD

**Issue by rsuchecki** [plantinformatics/pretzel#62]
Data set names are unique in the DB, consequently a user is unable to upload a data set if it is already present in the DB even though it may be inaccessible to that user. 

```
Unhandled error for request POST /api/Datasets/upload: MongoError: E11000 duplicate key error collection: pretzel.Dataset index: _id_ dup key: { : "Triticum_aestivum_IWGSC_RefSeq_v1.0_90k_markers" }
    at Function.MongoError.create (/home/rad/pretzel/backend/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/rad/pretzel/backend/node_modules/mongodb/lib/utils.js:139:22)
    at /home/rad/pretzel/backend/node_modules/mongodb/lib/collection.js:668:23
    at handleCallback (/home/rad/pretzel/backend/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/home/rad/pretzel/backend/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /home/rad/pretzel/backend/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

We have discussed this on [previously](https://plantinformatics.slack.com/archives/C6L61UBGD/p1528850775000020), but should re-visit the issue, as it is likely to become more pressing as the number of users increases.  

Observed in c9f06fd4b3

**Comment by Gruek** [comment]
This issue is fixed in this commit https://github.com/plantinformatics/pretzel/commit/d69b6fec6cda23d67e932dd111878c87eb7c5382

dataset now has an auto generated unique id
